const CATEGORIES = [
    { cat: 'Hotels',subcat:[ 
        {cat: 'Book Rooms'},
        {cat: 'Cabs'},
    ]},
    { cat: 'Food',subcat:[
        {cat: 'Pizza'},
        {cat: 'Chinese'},
    ]},
    // { cat: 'Retail',subcat:[
    //     {cat: 'Cloths'},
    //     {cat: 'Grocery'},
    //     {cat: 'Food'},
    //     {cat: 'Consumer Electronics'},
    //     {cat: 'FMCG items'},
    //     {cat: 'Kitchen ware'},
    //     {cat: 'Beauty'},
    //     {cat: 'Gardening'},
    //     {cat: 'Customized'},
    //     {cat: 'Shoes'},
    //     {cat: 'Gadgets'},
    //     {cat: 'Furniture'},
    //     {cat: 'Stationary'},
    //     {cat: 'Electronics Components'},
    // ]},
    // { cat: 'Industrial',subcat:[
    //     {cat: 'Solvents / Chemicals'},
    //     {cat: 'Machinery'},
    //     {cat: 'Plant Setups'},
    //     {cat: 'Injection Moulding'},
    //     {cat: 'Packaging Print'},
    //     {cat: 'CNC Services'},
    //     {cat: 'Lab equipments'},
    //     {cat: 'Robotic Arms'},
    //     {cat: 'Safety'},
    //     {cat: 'Ladders'},
    //     {cat: 'Forklift'},
    //     {cat: 'Sensors'},
    //     {cat: 'Heaters / Ovens'},
    //     {cat: 'Motors'},
    //     {cat: 'Controllers'},
    //     {cat: 'Electrical Components'},
    // ]},
    // { cat: 'Farming',subcat:[
    //     {cat: 'Drone'},
    //     {cat: 'Farm Equipments'},
    //     {cat: 'Solar pumps'},
    //     {cat: 'Fencing'},
    //     {cat: 'Tractors'},
    //     {cat: 'Tube well pipes'},
    //     {cat: 'Seeds'},
    //     {cat: 'Growing Tech'},
    //     {cat: 'Consultant'},
    //     {cat: 'Farm Chemicals'},
    //     {cat: 'Indoor Farming'},
    // ]},
    // { cat: 'College',subcat:[
    //     {cat: 'Find Colleges'},
    //     {cat: 'Campus Buzz'},
    //     {cat: 'Research News'},
    //     {cat: 'Find Intern'},
    //     {cat: 'Startup Products'},
    // ]},
    // { cat: 'Book Tickets',subcat:[
    //     {cat: 'Flights'},
    //     {cat: 'Trains'},
    //     {cat: 'Buses'},
    //     {cat: 'Metros'},
    //     {cat: 'Movies'},
    // ]},
    // { cat: 'Rent',subcat:[
    //     {cat: 'Flats/House'},
    //     {cat: 'Furniture'},
    //     {cat: 'Car / e-Rickshaw'},
    //     {cat: 'Machine'},
    //     {cat: 'Factory Space'},
    // ]},
    // { cat: 'Interior',subcat:[
    //     {cat: 'Sinks'},
    //     {cat: 'Bath tubs'},
    //     {cat: 'Dump Pots'},
    //     {cat: 'Tiles'},
    //     {cat: 'Marble'},
    //     {cat: 'Crosslink Blocks'},
    // ]},
    // { cat: 'Hardware',subcat:[
    //     {cat: 'Nuts / Bolts'},
    //     {cat: 'Wrinches'},
    //     {cat: 'Hammer / Chisels'},
    //     {cat: 'Tiles'},
    //     {cat: 'Saw'},
    //     {cat: 'Sand-paper'},
    // ]},
    // { cat: 'Home Electricals',subcat:[
    //     {cat: 'Wires'},
    //     {cat: 'Switches'},
    //     {cat: 'MCB Box'},
    //     {cat: 'Tapes'},
    //     {cat: 'PVC Pipes'},
    //     {cat: 'Meters'},
    // ]},
    // { cat: 'Delivery Driver',subcat:[
    //     {cat: 'Food'},
    //     {cat: 'Post'},
    //     {cat: 'Car Driver'},
    //     {cat: 'Bike Driver'},
    // ]},
    // { cat: 'Find Location',subcat:[
    //     {cat: 'Metros'},
    //     {cat: 'Trains'},
    //     {cat: 'InterCity Buses'},
    //     {cat: 'State Buses'},
    //     {cat: 'School Van/Bus'},
    //     {cat: 'Police Stations'},
    //     {cat: 'Shops'},
    //     {cat: 'EV Chargers'},
    //     {cat: 'Petrol pumps'},
    //     {cat: 'Library'},
    //     {cat: 'Schools'},
    //     {cat: 'Banks'},
    // ]},
    // { cat: 'Puja-Paath',subcat:[
    //     {cat: 'Mandir'},
    //     {cat: 'Book Pandit'},
    //     {cat: 'Find Jyotishi'},
    //     {cat: 'Organize Hawan'},
    //     {cat: 'Ramayana path'},
    //     {cat: 'Bhajan Mandali'},
    //     {cat: 'Upcoming Events'},
    //     {cat: 'Charity / Donation'},
    // ]},
    // { cat: 'Blogs',subcat:[
    //     {cat: 'Food'},
    //     {cat: 'Technology'},
    //     {cat: 'Science'},
    //     {cat: 'Art'},
    //     {cat: 'Personal Devpt.'},
    //     {cat: 'Healthcare'},
    // ]},
    // { cat: 'Medical',subcat:[
    //     {cat: 'Hospitals'},
    //     {cat: 'Call Doctor'},
    //     {cat: 'Emergency'},
    //     {cat: 'Buy Medicine'},
    //     {cat: 'Medical Equipments'},
    //     {cat: 'Oxygen'},
    //     {cat: 'Donate Organ'},
    //     {cat: 'Blood Bank'},
    //     {cat: 'Drone Organ Delivery'},
    //     {cat: 'Funeral services'},
    // ]},
    // { cat: 'Shaadi / Baraat',subcat:[
    //     {cat: 'Find Life Partner'},
    //     {cat: 'Guest House'},
    //     {cat: 'Makeup Artist'},
    //     {cat: 'Catering'},
    //     {cat: 'Decoration'},
    //     {cat: 'Pandit'},
    //     {cat: 'Band / DJ'},
    //     {cat: 'Invitation Card'},
    //     {cat: 'Photography'},
    // ]},
    // { cat: 'Transport',subcat:[
    //     {cat: 'Trucks'},
    //     {cat: 'Mini Loader'},
    //     {cat: 'Loader'},
    //     {cat: 'School Bus'},
    //     {cat: 'Cranes'},
    //     {cat: 'Tractor'},
    // ]},
    // { cat: 'Real-State',subcat:[
    //     {cat: 'Flats'},
    //     {cat: 'Houses'},
    //     {cat: 'Villas'},
    //     {cat: 'Shops'},
    //     {cat: 'Plots'},
    //     {cat: 'Factory'},
    // ]},
    // { cat: 'Jobs / Openings',subcat:[
    //     {cat: 'Teacher'},
    //     {cat: 'IT Engineer'},
    //     {cat: 'Guards'},
    //     {cat: 'Salesman'},
    //     {cat: 'Managers'},
    //     {cat: 'Nurses'},
    //     {cat: 'Workers'},
    //     {cat: 'Lawyer'},
    //     {cat: 'Accountants'},
    // ]},
    // { cat: 'Advertise',subcat:[
    //     {cat: 'Upcoming Events'},
    //     {cat: 'Newspaper Ads'},
    //     {cat: 'Radio Ads'},
    //     {cat: 'MobileApp Ads'},
    //     {cat: 'Pamphlets'},
    //     {cat: 'Flex Print'},
    //     {cat: 'LED Display Ads'},
    //     {cat: 'Online Ads'},
    // ]},
    // { cat: 'Mapping',subcat:[
    //     {cat: 'Groundwater '},
    //     {cat: 'Air quality index'},
    //     {cat: 'Industries'},
    // ]},
    // { cat: 'Bills / Payments',subcat:[
    //     {cat: 'Mobile Recharge'},
    //     {cat: 'Electricity'},
    //     {cat: 'Gas'},
    //     {cat: 'Water'},
    // ]},
    // { cat: 'Finance',subcat:[
    //     {cat: 'Stocks'},
    //     {cat: 'Policies'},
    //     {cat: 'SIP'},
    //     {cat: 'Bank Loan'},
    //     {cat: 'Micro Finance'},
    // ]},
    // { cat: 'Utilities',subcat:[
    //     {cat: 'Contractor'},
    //     {cat: 'Plumber'},
    //     {cat: 'Electrician'},
    //     {cat: 'Car/Bike Service'},
    //     {cat: 'EV Conversion'},
    //     {cat: 'Lost and Found'},
    // ]},
];

export function getCategories() { 
    return CATEGORIES;
} 